name: Push Container to Docker Hub

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DockerHub_User }} --password ${{ secrets.DockerHub_API_KEY }}
    - name: Build and push
      run: docker-compose build
      run: docker-compose push